package com.ysyl.common.schema.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Yydconfig generated by Tools.Don't edit.
 */
@Entity
@Table(name = "yydconfig")
public class Yydconfig implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 配置代码 */
	private YydconfigId id;
	/** 配置项名称 */
	private String configName;
	/** 参数值 */
	private String configValue;
	/** 任务有效状态 */
	private String valid;
	/** 标志 */
	private String flag;
	/** 备注 */
	private String remark;

	public Yydconfig() {
	}

	/**       
	 * 配置代码
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "type", column = @Column(name = "type")),
			@AttributeOverride(name = "configCode", column = @Column(name = "configCode")) })
	public YydconfigId getId() {
		return this.id;
	}

	public void setId(YydconfigId id) {
		this.id = id;
	}

	/**       
	 * 配置项名称
	 */

	@Column(name = "configName")
	public String getConfigName() {
		return this.configName;
	}

	public void setConfigName(String configName) {
		this.configName = configName;
	}

	/**       
	 * 参数值
	 */

	@Column(name = "configValue")
	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

	/**       
	 * 任务有效状态
	 */

	@Column(name = "valid")
	public String getValid() {
		return this.valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	/**       
	 * 标志
	 */

	@Column(name = "flag")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**       
	 * 备注
	 */

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
