package com.ysyl.common.schema.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * YydconfigId generated by Tools.Don't edit.
 */
@Embeddable
public class YydconfigId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String type;
	private String configCode;

	public YydconfigId() {
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "configCode")
	public String getConfigCode() {
		return this.configCode;
	}

	public void setConfigCode(String configCode) {
		this.configCode = configCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof YydconfigId))
			return false;
		YydconfigId castOther = (YydconfigId) other;

		return ((this.getType() == castOther.getType()) || (this.getType() != null
				&& castOther.getType() != null && this.getType().equals(
				castOther.getType())))
				&& ((this.getConfigCode() == castOther.getConfigCode()) || (this
						.getConfigCode() != null
						&& castOther.getConfigCode() != null && this
						.getConfigCode().equals(castOther.getConfigCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37
				* result
				+ (getConfigCode() == null ? 0 : this.getConfigCode()
						.hashCode());
		return result;
	}

}
