package com.ysyl.common.schema.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Yyverify generated by Tools.Don't edit.
 */
@Entity
@Table(name = "yyverify")
public class Yyverify implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	/**
	 * 商品大类Id，序列自增长
	 */
	private Long id;
	/** 手机号 */
	private String mobile;
	/** 类型 1-商户注册验证 2-摄影工作室*/
	private String type;
	/** 验证码 */
	private Integer verifyNo;
	/** 创建时间 */
	private Date createTime;
	/** 过期时间  */
	private Date expiredTime;

	public Yyverify() {
	}

	/**       
	 * Id
	 */
	@SequenceGenerator(name = "generator", allocationSize = 1, sequenceName = "YyVerify")
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "generator")
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "mobile")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "verifyNo")
	public Integer getVerifyNo() {
		return this.verifyNo;
	}

	public void setVerifyNo(Integer verifyNo) {
		this.verifyNo = verifyNo;
	}


	@Column(name = "createtime")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "expiredtime")
	public Date getExpiredTime() {
		return this.expiredTime;
	}

	public void setExpiredTime(Date expiredTime) {
		this.expiredTime = expiredTime;
	}

}
