package com.ysyl.common.schema.model;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * YyverifyId generated by Tools.Don't edit.
 */
@Embeddable
public class YyverifyId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	/** 手机号 */
	private String mobile;
	/** 类型 1-商户注册验证 */
	private String type;

	public YyverifyId() {
	}

	@Column(name = "mobile")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof YyverifyId))
			return false;
		YyverifyId castOther = (YyverifyId) other;

		return ((this.getMobile() == castOther.getMobile()) || (this
				.getMobile() != null && castOther.getMobile() != null && this
				.getMobile().equals(castOther.getMobile())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMobile() == null ? 0 : this.getMobile().hashCode());
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		return result;
	}

}
